language: dart
sudo: required
dart:
  - stable
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - sudo cp ci/pg_hba.conf /etc/postgresql/9.6/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database dart_test;' -U postgres
  - psql -c 'create user dart with createdb;' -U postgres
  - psql -c "alter user dart with password 'dart';" -U postgres
  - psql -c 'grant all on database dart_test to dart;' -U postgres
  - psql -c 'create user darttrust with createdb;' -U postgres
  - psql -c 'grant all on database dart_test to darttrust;' -U postgres
  - pub get
#script: bash ci/script.sh
dart_task:
  - test: --run-skipped -r expanded -j 1
  - dartfmt
  - dartanalyzer: --fatal-infos --fatal-warnings .

#after_success: bash ci/after_script.sh
branches:
  only:
    - master